### ISSUE TITLE
`vsphere-iso`: Incorrect `GuestOsIdentifier` in OVF

### ISSUE THREAD

**Issue by MattMonkman** [hashicorp/packer-plugin-vsphere#194]
- Please keep this note for the community --->

 

#### Community Note

 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request

* If you are interested in working on this issue or have submitted a pull request, please leave a comment

 

 

When filing a bug, please include the following headings if possible. Any

example text in this template can be deleted.

 

#### Overview of the Issue

I'm using the packer vsphere iso builder to create Windows 2019 images that will be consumed on different versions of vSphere, 6.5, 6.7, 7.02.  VM hardware version is 13 to offer the most compatibility across the vSphere environment.

 

I'm building on vSphere 7.02, using the export to content library feature and creating an ovf.

 

When deploying a vm from the ovf, it fails to boot with guest os invalid.  On editing the vm settings I find that neither Guest OS or Guest OS version are populated.  Due to vm h/w 13, Windows 2016 is the highest os version that can be selected and on doing so, the VM boots up successfully.

I've downloaded the OVF file to find the osType is incorrect;
```
<OperatingSystemSection ovf:id="112" vmw:osType="windows2019srv_64Guest">

<Info>The operating system installed</Info>

<Description>Microsoft Windows Server 2016 or later (64-bit)</Description>

</OperatingSystemSection>
```

**windows2019srv_64Guest** is not known at vm h/w 13 hence the boot failure.

I also export the ovf and upload it to a s/w repo.  On checking the ovf, the osType is correct.

```
    <OperatingSystemSection ovf:id="1" vmw:osType="windows9Server64Guest">

      <Info>The kind of installed guest operating system</Info>

      <Description>Microsoft Windows Server 2016 or later (64-bit)</Description>

    </OperatingSystemSection>
```

**windows9Server64Guest** is correct for Microsoft Windows Server 2016 or later (64-bit)

 
Can you explain the differences between the "content_library_destination" process and the "export" process?

Both trigger an "Export OVF template" task in vCentre.
"content_library_destination" is initiated by vpxd-extension-"uuid" user.
"Export" is initiated by the user Packer uses to connect to vCentre.

"Export" produces the correct OVF.

#### Reproduction Steps

Build a vm with the following packer template properties included:

guest_os_type = windows9Server64Guest

vm_version =13

Check the osType in the ovf on the content library datastore

Check the osType in the ovf at the export folder location

### Packer version

1.7.8 & 1.8.0

### Operating system and Environment details

vSphere version 7.0.2.00400
VMware ESXi, 7.0.2, 18426014

Guest OS - Windows 2019
Packer running on Jenkins Linux agents

**Comment by tenthirtyam** [comment]
Please note: The End of General Support for **both** vSphere 6.5 and vSphere 6.7 is **October 15, 2022**. 

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by MattMonkman** [comment]
The issue has nothing to do with vSphere 6.5 or 6.7. I'm building on 7.02. Is anyone actually looking into the problem?

**Comment by tenthirtyam** [comment]
vSphere is maintaining the actual guest OS identifier.

The guestOS string in the VMX file is used to set up and power on a VM. It doesn't necessary map directly to what the guest contains. When the guest runs and tools are present, the guest identification code analyzes the guest and returns the "short name" (same format as the guestOS in the VMX) of what it has found (along with the "long name" and "detailed data").

These data are passed on to `hostd` and so on up the software stack - it reports what's **actually** present.

If you need to suppress this for a particular use case, you can force the identification process to return what you want (a constant). To do this, you can use the guest identification override feature, a setting in the tools configuration file (`tools.conf`).

For example, if I wanted to force Debian 11 to be "Other 4.x or later Linux (64-bit)" so that I could perform guest customization via VM Tools when cloning from the content library, I'd need to suppress the identification process of `debian11_64Guest`.  

To do this, I'd force the identification in the tools configuration:

```vim
[guestosinfo]
short-name = other4xLinux64Guest
```

Using this method, you could update the tools configuration of the Window Server 2019 machine image to enforce the following during the build process, which would need to be done use a provisioner (_e.g._, PowerShell,  Ansible)

```vim
[guestosinfo]
short-name = windows9Server64Guest
```

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
A [recommended solution](https://github.com/hashicorp/packer-plugin-vsphere/issues/194#issuecomment-1267875311) has been provided - if there is no further activity on this `question` within the next 7 days it will be closed.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by MattMonkman** [comment]
Thanks for taking the time to reply Ryan
 I've not yet worked through your recommended solution as I implemented a work around some months  ago now.

It's not clear why there's a different outcome using option: content_library_destination vs Export (to file system).

I'm exporting the ovf to a file system and using powercli to import the ovf to content library outside of the packer process. This works and new vms created from the ovf boot up OK.
