### ISSUE TITLE
Plugin release and pathes cadence & road map

### ISSUE THREAD

**Issue by luis-garza** [hashicorp/packer-plugin-vsphere#90]
Latest plugin version was released 1 month ago, in the meantime several nice patches were merge into main like #87

I'm wondering if there is an agreed cadence or road map for new releases and patches?

I guess with the new plugin architecture it isn't a huge deal publish a patch once it's merged into master, as one can stick to a pinned version.

Is there any workflow & road map agreed for Packer plugins?
Thanks!

**Comment by sylviamoss** [comment]
Hi @luis-garza, thanks for reaching out. We don't have any fixed agreed cadence or road map for nor plugin's releases. Currently, the Packer team has been focused on a project and we've been joining forces to release all of the plugins when we release Packer but that's not a rule. We release other plugins at another time when needed. 
You're right, pushing a new plugin release is pretty simple. I can push a vsphere one since there are a lot of interesting changes since the last one!

**Comment by luis-garza** [comment]
Thanks for the info! Great to know the release process will be decoupled in near future. :crossed_fingers: 

In the meantime I'll really appreciate some patched versions from time to time... :innocent:

**Comment by sylviamoss** [comment]
Hello! I've just released v1.0.1 🎉

**Comment by luis-garza** [comment]
Yahoo! :clap:

Thanks for releasing it, now we can remove nasty hacks in our CD pipelines!
